### ISSUE TITLE
unexpand Not working with empty string

### ISSUE THREAD

**Issue by araraloren** [Altai-man/perl6-Text-Tabs#4]
When I tried this 
`perl6 -e 'use Text::Tabs; say unexpand(["", ])' `

Rakudo (This is Rakudo version 2017.04.3 built on MoarVM version 2017.04-44-gf0db882) complain:
Type check failed for return value; expected Array but got Any (Any)
  in sub expand at /perl6/share/perl6/site/sources/CB069F052EBCAE0EEB6CCE926DE9C999A0A52436 (Text::Tabs) line 16
  in sub unexpand at /perl6/share/perl6/site/sources/CB069F052EBCAE0EEB6CCE926DE9C999A0A52436 (Text::Tabs) line 26
  in block <unit> at -e line 1

**Comment by Altai-man** [comment]
Thank you very much for experiments and reporting! Latest commit hopefully fixed it, so closing now.
